import Head from "next/head"
import React from "react"
import CardProfile from "../components/card-profile"
import Button from "../components/button"
import { StyledMain, StyledDescription } from "./styles"
import Skills from "../components/skills"

export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Hola soy Ricardo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <CardProfile />

        <Button as="a" href="/file.pdf" target="_blank">
          DOWNLOAD CV
        </Button>

        <StyledDescription>
          Hello! I’m Robert Smith. Senior Web Developer specializing in front end development. Experienced with all
          stages of the development cycle for dynamic web projects. Well-versed in numerous programming languages
          including and C. Stng background in project management and customer relations.
        </StyledDescription>

        <Skills />
      </StyledMain>
    </React.Fragment>
  )
}
