import Head from "next/head"
import React from "react";
import CardProfile from "../components/card-profile"
import Button from "../components/button"
import { StyledMain } from "./styles"



export default function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Hola soy Ricardo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <CardProfile />
        <Button>DOWNLOAD CV</Button>
      </StyledMain>
  </React.Fragment>
  );
}
