import Head from "next/head"
import React from "react"
import { useTranslation } from "react-i18next"
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import CardProfile from "../components/card-profile"
import Button from "../components/button"
import { StyledMain, StyledDescription, StyledLanguage } from "./styles"
import Skills from "../components/skills"
import { createGlobalStyle } from "styled-components"


const GlobalStyle = createGlobalStyle`
  body {
    --primary-color: ${({ isEnglish }) =>  isEnglish? '#00bcd4' : '#e8676a'};
  }
`

export default function Home() {
  const { i18n } = useTranslation();
  const isEnglish = i18n.language === 'en';
  const toggleLanguage = () => {
    i18n.changeLanguage(isEnglish? 'es' : 'en')
  }
  return (
    <React.Fragment>
      <GlobalStyle isEnglish={isEnglish} />
      <Head>
        <title>Hola soy Ricardo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMain>
        <StyledLanguage isEnglish={isEnglish} onClick={toggleLanguage} >
        {i18n.language}
        </StyledLanguage >
        <CardProfile />

        <Button as="a" href="/file.pdf" target="_blank">
          DOWNLOAD CV
        </Button>

        <StyledDescription>
          Hello! I’m Robert Smith. Senior Web Developer specializing in front end development. Experienced with all
          stages of the development cycle for dynamic web projects. Well-versed in numerous programming languages
          including and C. Stng background in project management and customer relations.
        </StyledDescription>

        <Skills />
      </StyledMain>
    </React.Fragment>
  )
}


export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['common', 'footer']),
  },
})
